FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy schema files and schema registry client
COPY app.py .
COPY schema_registry_client.py .
COPY dlq_handler.py .
COPY ../../schemas/avro/ /app/schemas/avro/

CMD ["python", "app.py"]

