FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Krijo static folder nëse nuk ekziston
RUN mkdir -p static

EXPOSE 8080

CMD ["python", "app.py"]

